# Generated by Django 6.0 on 2026-01-06 23:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="URL identifier",
                    ),
                ),
                ("url", models.TextField(verbose_name="Original URL")),
            ],
            options={
                "verbose_name": "url",
                "verbose_name_plural": "urls",
            },
        ),
    ]
