# Generated by Django 6.0.1 on 2026-01-07 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Slug can only contain letters, numbers, hyphens, and underscores.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
                verbose_name="URL slug",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=2048, verbose_name="Original URL"),
        ),
    ]
